[project]
name = "tripbuddy"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
  "Flask==3.0.3",
  "pyTelegramBotAPI==4.28.0",
  "gunicorn==21.2.0",
]

[tool.uv]
# uv — менеджер зависимостей, который использует Replit Autoscale
